name: CI/CD

on: [push]

jobs:
  build:
    name: Run Symfony Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, pdo, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Wait for MySQL
        run: sleep 10

      - name: Prepare the database
        env:
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/symfony"
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run PHPUnit tests
        run: php bin/phpunit
        env:
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/symfony"

      - name: Run PHPStan
        run: ./vendor/bin/phpstan
